# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 650)
        MainWindow.setMinimumSize(QtCore.QSize(400, 650))
        MainWindow.setMaximumSize(QtCore.QSize(400, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outputLabel = QtWidgets.QLabel(self.frame)
        self.outputLabel.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 87 14pt \"Arial Black\";\n"
"font: 87 40pt \"Arial Black\";\n"
"color:#fff")
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout.addWidget(self.outputLabel)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(167, 224, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.clearButtuon = QtWidgets.QPushButton(self.frame_6)
        self.clearButtuon.setMinimumSize(QtCore.QSize(90, 100))
        self.clearButtuon.setMaximumSize(QtCore.QSize(90, 100))
        self.clearButtuon.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.clearButtuon.setObjectName("clearButtuon")
        self.horizontalLayout_12.addWidget(self.clearButtuon)
        self.porcentagemButton = QtWidgets.QPushButton(self.frame_6)
        self.porcentagemButton.setMinimumSize(QtCore.QSize(90, 100))
        self.porcentagemButton.setMaximumSize(QtCore.QSize(90, 100))
        self.porcentagemButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.porcentagemButton.setObjectName("porcentagemButton")
        self.horizontalLayout_12.addWidget(self.porcentagemButton)
        self.backspaceButton = QtWidgets.QPushButton(self.frame_6)
        self.backspaceButton.setMinimumSize(QtCore.QSize(90, 100))
        self.backspaceButton.setMaximumSize(QtCore.QSize(90, 100))
        self.backspaceButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.backspaceButton.setObjectName("backspaceButton")
        self.horizontalLayout_12.addWidget(self.backspaceButton)
        self.divisaoButton = QtWidgets.QPushButton(self.frame_6)
        self.divisaoButton.setMinimumSize(QtCore.QSize(90, 100))
        self.divisaoButton.setMaximumSize(QtCore.QSize(90, 100))
        self.divisaoButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.divisaoButton.setObjectName("divisaoButton")
        self.horizontalLayout_12.addWidget(self.divisaoButton)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(167, 224, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.seteButton = QtWidgets.QPushButton(self.frame_5)
        self.seteButton.setMinimumSize(QtCore.QSize(90, 100))
        self.seteButton.setMaximumSize(QtCore.QSize(90, 100))
        self.seteButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.seteButton.setObjectName("seteButton")
        self.horizontalLayout_5.addWidget(self.seteButton)
        self.oitoButton = QtWidgets.QPushButton(self.frame_5)
        self.oitoButton.setMinimumSize(QtCore.QSize(90, 100))
        self.oitoButton.setMaximumSize(QtCore.QSize(90, 100))
        self.oitoButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.oitoButton.setObjectName("oitoButton")
        self.horizontalLayout_5.addWidget(self.oitoButton)
        self.noveButton = QtWidgets.QPushButton(self.frame_5)
        self.noveButton.setMinimumSize(QtCore.QSize(90, 100))
        self.noveButton.setMaximumSize(QtCore.QSize(90, 100))
        self.noveButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.noveButton.setObjectName("noveButton")
        self.horizontalLayout_5.addWidget(self.noveButton)
        self.multiplicacaoButton = QtWidgets.QPushButton(self.frame_5)
        self.multiplicacaoButton.setMinimumSize(QtCore.QSize(90, 100))
        self.multiplicacaoButton.setMaximumSize(QtCore.QSize(90, 100))
        self.multiplicacaoButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.multiplicacaoButton.setObjectName("multiplicacaoButton")
        self.horizontalLayout_5.addWidget(self.multiplicacaoButton)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(167, 224, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.quatroButton = QtWidgets.QPushButton(self.frame_4)
        self.quatroButton.setMinimumSize(QtCore.QSize(90, 100))
        self.quatroButton.setMaximumSize(QtCore.QSize(90, 100))
        self.quatroButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.quatroButton.setObjectName("quatroButton")
        self.horizontalLayout_4.addWidget(self.quatroButton)
        self.cincoButton = QtWidgets.QPushButton(self.frame_4)
        self.cincoButton.setMinimumSize(QtCore.QSize(90, 100))
        self.cincoButton.setMaximumSize(QtCore.QSize(90, 100))
        self.cincoButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.cincoButton.setObjectName("cincoButton")
        self.horizontalLayout_4.addWidget(self.cincoButton)
        self.seisButton = QtWidgets.QPushButton(self.frame_4)
        self.seisButton.setMinimumSize(QtCore.QSize(90, 100))
        self.seisButton.setMaximumSize(QtCore.QSize(90, 100))
        self.seisButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.seisButton.setObjectName("seisButton")
        self.horizontalLayout_4.addWidget(self.seisButton)
        self.adicaoButton = QtWidgets.QPushButton(self.frame_4)
        self.adicaoButton.setMinimumSize(QtCore.QSize(90, 100))
        self.adicaoButton.setMaximumSize(QtCore.QSize(90, 100))
        self.adicaoButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.adicaoButton.setObjectName("adicaoButton")
        self.horizontalLayout_4.addWidget(self.adicaoButton)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(167, 224, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.umButton = QtWidgets.QPushButton(self.frame_3)
        self.umButton.setMinimumSize(QtCore.QSize(90, 100))
        self.umButton.setMaximumSize(QtCore.QSize(90, 100))
        self.umButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.umButton.setObjectName("umButton")
        self.horizontalLayout_3.addWidget(self.umButton)
        self.doisButton = QtWidgets.QPushButton(self.frame_3)
        self.doisButton.setMinimumSize(QtCore.QSize(90, 100))
        self.doisButton.setMaximumSize(QtCore.QSize(90, 100))
        self.doisButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.doisButton.setObjectName("doisButton")
        self.horizontalLayout_3.addWidget(self.doisButton)
        self.tresButton = QtWidgets.QPushButton(self.frame_3)
        self.tresButton.setMinimumSize(QtCore.QSize(90, 100))
        self.tresButton.setMaximumSize(QtCore.QSize(90, 100))
        self.tresButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.tresButton.setObjectName("tresButton")
        self.horizontalLayout_3.addWidget(self.tresButton)
        self.subtracaoButton = QtWidgets.QPushButton(self.frame_3)
        self.subtracaoButton.setMinimumSize(QtCore.QSize(90, 100))
        self.subtracaoButton.setMaximumSize(QtCore.QSize(90, 100))
        self.subtracaoButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.subtracaoButton.setObjectName("subtracaoButton")
        self.horizontalLayout_3.addWidget(self.subtracaoButton)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(167, 224, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.zeroButton = QtWidgets.QPushButton(self.frame_2)
        self.zeroButton.setMinimumSize(QtCore.QSize(90, 100))
        self.zeroButton.setMaximumSize(QtCore.QSize(90, 100))
        self.zeroButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.zeroButton.setObjectName("zeroButton")
        self.horizontalLayout_2.addWidget(self.zeroButton)
        self.maisMenosButton = QtWidgets.QPushButton(self.frame_2)
        self.maisMenosButton.setMinimumSize(QtCore.QSize(90, 100))
        self.maisMenosButton.setMaximumSize(QtCore.QSize(90, 100))
        self.maisMenosButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.maisMenosButton.setObjectName("maisMenosButton")
        self.horizontalLayout_2.addWidget(self.maisMenosButton)
        self.pontoButton = QtWidgets.QPushButton(self.frame_2)
        self.pontoButton.setMinimumSize(QtCore.QSize(90, 100))
        self.pontoButton.setMaximumSize(QtCore.QSize(90, 100))
        self.pontoButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.pontoButton.setObjectName("pontoButton")
        self.horizontalLayout_2.addWidget(self.pontoButton)
        self.igualButton = QtWidgets.QPushButton(self.frame_2)
        self.igualButton.setMinimumSize(QtCore.QSize(90, 100))
        self.igualButton.setMaximumSize(QtCore.QSize(90, 100))
        self.igualButton.setStyleSheet("background-color: rgb(30, 150, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";")
        self.igualButton.setObjectName("igualButton")
        self.horizontalLayout_2.addWidget(self.igualButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora Python"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.clearButtuon.setText(_translate("MainWindow", "ac"))
        self.porcentagemButton.setText(_translate("MainWindow", "%"))
        self.backspaceButton.setText(_translate("MainWindow", "<<"))
        self.divisaoButton.setText(_translate("MainWindow", "/"))
        self.seteButton.setText(_translate("MainWindow", "7"))
        self.oitoButton.setText(_translate("MainWindow", "8"))
        self.noveButton.setText(_translate("MainWindow", "9"))
        self.multiplicacaoButton.setText(_translate("MainWindow", "*"))
        self.quatroButton.setText(_translate("MainWindow", "4"))
        self.cincoButton.setText(_translate("MainWindow", "5"))
        self.seisButton.setText(_translate("MainWindow", "6"))
        self.adicaoButton.setText(_translate("MainWindow", "+"))
        self.umButton.setText(_translate("MainWindow", "1"))
        self.doisButton.setText(_translate("MainWindow", "2"))
        self.tresButton.setText(_translate("MainWindow", "3"))
        self.subtracaoButton.setText(_translate("MainWindow", "-"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.maisMenosButton.setText(_translate("MainWindow", "+/-"))
        self.pontoButton.setText(_translate("MainWindow", "."))
        self.igualButton.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
